name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: My first step
        uses: ./
        with:
          owner: hadialqattan
          repository: pycln
          workflow: CI
