########[CI PIPELINE FLOW]########
# Run pre-commit:                #
#   | failure ~> stop.           #
#   | pass:                      #
#       Run tests:               #
#          | failure ~> stop.    #
#          | pass:               #
#             Upload coverage.   #
##################################
# Requiered Github secrets:      #
#   - CODECOV_TOKEN              #
##################################

name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: My first step
        uses: ./
        with:
          owner: hadialqattan
          repository: pycln
          workflow: CI
