name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: hadialqattan/gh-actions-sandbox@master
        with:
          owner: hadialqattan
          repository: pycln
          workflow: CI
          
